CMakeLists: fix build error adding some dependencies The build process was failing due to "undefined reference to symbol 'dladdr@@GLIBC_2.2.5'". Adding ${CMAKE_DL_LIBS} to CMakeLists fixes the build.